### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by shinnn** [BrowserSync/browser-sync-core#1]

**Comment by shakyShane** [comment]
An experiment/attempt to create a smaller core that addresses many issues from the main repo. Also after 2 years of use, I have a very solid idea of how the plugin system should work. So at the end of this experiment we'll finally be able to roll out docs for plugin authors as well as enabling many more cool features.

Mainly: 

1. dynamic client js
2. dynamic middleware
3. async resolution of plugins (like the ui for example)
4. smarter file-watching (mostly for plugin authors)
5. unified middleware management
6. strict mode

etc, etc
